sudo: false
language: ruby
cache: bundler
rvm:
- 2.6.6
install:
- bundle install
before_script:
- git config --global user.email "jnu2345@gmail.com"
- git config --global user.name "wind-flow"
script: bundle exec rake site:deploy --quiet
env:
  global:
  - secure: c0WTDFsoviaTerN8lG8eXZTKYqSWuXxaV0cuGxkcy+YF6f0KRSnSEzSAHtBrZRe3w4QP2PyDwNYe/3zGsC8/Km8AfDeJGzQDlkpA5kXF1RPmThiRn8KY5/AvvwB5SN5XQIgVxMJQxL/F96sCFxy4USeIOr+OR1cKsnj1OPYUBSsmOQuPPnyfmMmQjHwC1mSCOucgPZOjolO4MsdalaQLpo4UxQL8n9UDsONIOYUyjNb8vqOQ/Y3wnrpw6IvNgD4piMpdTFgDLJMq7uQo0i1YQOJnAEn7VNu9em/oH2RILrRuUlJA3qk6sF7aILbdLqCcGGzYfGv45ocGkwJRepbSo8V00Z4O1ElJxMYd7q5xR5MQkyaATZX5LdhjjwH4TWhCKJAyU8+ny6WWfkm28bjdo8lds1Q8Mk1VZ2L3DFTAqvKm9BKZWu3ao/d09Ge0iXp7KJGJwcFuaFb+EPrBd/mxkmbzJNd9j0XLhK0UUZsNey1CVfHNoWKvevxarXGoDLQITdws79JcAIfcZkHVJ5T47wfme9KtKilpZ6aAbZ1C5tQzbmLf6mvJKAKP7gvDkruybSq+Zd3GKQQYIWqCLXzNIkg2oz3jHlnQXlTw8ifHnVcGYD2h9XrYKjNJZnSR1y62Z8FURWZE881mNk3fPyJepLjBhG/y+dmNSxxS3U2lEO8=
  - secure: HFwIQTddxQ/+L8UlU/Xi1vLM1b53WHr9hocCkhC9UGdilNVzzHq2DdH1stCLhV1lzRX+tvvS1y2MAN/NxNSXGFwZ/XhsAG+BvV3pmX4Kh8LemE6+9QeUvDKQZJODXRaoHxlhzUBTx591slBsG6TD8rb3ZVpz048RySZqlz512g8HquZxzfp04NM5lSwaqNouyUcpEFDexcs+tDu5FNKuEg36x79K4sGBSESoE42a3XirMSk20NcbwOVzxlHJDtTfkaspH0a/x+UVw4SeZCFtqweURQUFJO7g9/j5qOgpCm3syqizcmBop3qhcGapvAbhmhlXvMeM9UesO3sfRQbPX7irai5JSztpub8L+CCGHdbqWF1RpZRm+XmYdvq4g/Y9G0LFF7EtsHLERcEHUwPIBrlD3cI2jWomANeOa5dIaEN2ccHwClzxl6uuTLQUL1+kDsF+GwH3kgzj2FPLh3mT0oEAECPHK1cnZ3H5kJpkV2TJ0OdlIGI+siInJJN5zlfC4d8PGxAk2MY0gp4vk7M2VpseeNwn4nEKvMiSG+kf4BQAV8BFU8DLwi/ElLoxLYs70HyQVhy7vIncSo4TaGSRdzO/xp7R23i8zbC9eP2Fwlnp4arCRh0goDQ//LSgZ1R9W/sF7UzOpmqevuZSVCiXpx6lzN+lDw4AB7fCWfs+eY4=
  - secure: lU7oQ+tOHzLNH1DCNo02J+ttMHLLSwHqP9pHw5O/OSVnSRtnwGoMUSFqaSQcsi7Whz2jTxz2z9FdtwmxyGz1nd2iiNfsQ3za+1CmSJKZIllTE7xtjSGA2gBzrL00tv0+ylfiT1TdnTGKsG0vu6KaKd7RH8sMYMYKmvPjaAJZT/hbkiH46cCW9xQmzEmUuMcocpyupdStzUhU8IQFqv3IkG7zrJFOrmRpeta0YNaVEKe1LAk0jfDZ3le3SQzVLeXR0ABIFD2yB5tpV1ICHMUsFZsobb77m/nehFmF5pw9gOc4NidMzn9KIwA4JH21SmqLqQhR0a27UcEam7qj54PGx78o+L4LXPedkQw6bchXLs6CqQvbwG1zjl8qKHTYwEkh93GGloj1x+Xa3PWMOXd6sR+PtlzuSBU4qJmJ8IxYEInm6Khl9JjGdCUmX4sBJo9pM5x//mfM+PrVHLrM0cVtzmEphiM7aDj72DSdnMRATMJ6t8+48MqsKlF5Xyo02j4R/zX8B/Wym0/kSQFYbxOLuiVNUrLRXXy1fKcTQ2iyw86X4aRieEC8rKF0i/wXQ9tYT/J0BCc8OOraRrs0UHSJVlfChTO/juR2DPOtKx1C7pk5s7cwPOaJxN00C2llxhu8h9nOFiPsljXXqjMcS1D9m84PDTfoClue9NqaB/seWQs=
branches:
  only:
  - main
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $secure  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: main