sudo: false
language: ruby
cache:
  directories:
  - "/home/travis/.rvm/"
rvm:
- 2.6.6
install:
- bundle install
before_script:
- git config --global user.email "jnu2345@gmail.com"
- git config --global user.name "wind-flow"
script: bundle exec rake site:deploy --quiet
env:
  global:
    secure: lrR3o170lleJMMaCAWenwkDauJhd84ShSUaAb8VCe6nGHRTQ2bxmBLH9tU7JGXlTgtVZKfRFKo1faMqik9b/FMRG3myrcqRRrPZNOuf8gnrIwecR70dL6nqPUvbNogBkbl8Y1CL7M06OxAjrHhFfwjjHD4DIhLCoOofONOb7sYhZHSNT6DU8TKvKNma6uFs+OYzWy9B2/Cx465NauqdsdQOWo2EkCDh97//Dp3qAKMM+Y6zqfjN5tHEEl5f1+AIt25E+G9txxBcOMvQLPU7wSgnkV38G/Z8XtvMZ4F+egm6M3Yotd4NyWdYgG5VqFuIFIpQe4bBjnXf+9MLQoVRQqN0PyNEswQCohyP3c86Y0TNdoMYa0eUO79FXXHr5b0mf2DMbCbQ/4mHbBp6TOid+NjEHmIBUNKH3rnML9c8yA/xncMXbk1ITGGNH8jaRcizCCjpweaW9S9Ozm95gTMU9OhbST7tPBQe16TncT86ZujfR8XZQRWbt6GvU3iSHVjqeBMe6iWkjfn2PsVD/F856WFLbi7MdiUJiJ9gMl7bTAeo4LgFPxw9Mz0k/K4xtacoRACJoQWHNG79ZdeGBzXbMvVVDh2asX6KbYy2i7zBiwqOcAVNT/ACNil+Hl89sRe0k8PEHOlmWFUxgsXG/p7iycI1TxwWvTzHnM1Ki81/+GdE=
branches:
  only:
  - main