sudo: false
language: ruby
cache: bundler
rvm:
- 2.6.6
install:
- bundle install
before_script:
- git config --global --unset credential.helper
- git config --global user.email "jnu2345@gmail.com"
- git config --global user.name "wind-flow"

script: bundle exec rake site:deploy --quiet
env:
  global:
  - secure: c0WTDFsoviaTerN8lG8eXZTKYqSWuXxaV0cuGxkcy+YF6f0KRSnSEzSAHtBrZRe3w4QP2PyDwNYe/3zGsC8/Km8AfDeJGzQDlkpA5kXF1RPmThiRn8KY5/AvvwB5SN5XQIgVxMJQxL/F96sCFxy4USeIOr+OR1cKsnj1OPYUBSsmOQuPPnyfmMmQjHwC1mSCOucgPZOjolO4MsdalaQLpo4UxQL8n9UDsONIOYUyjNb8vqOQ/Y3wnrpw6IvNgD4piMpdTFgDLJMq7uQo0i1YQOJnAEn7VNu9em/oH2RILrRuUlJA3qk6sF7aILbdLqCcGGzYfGv45ocGkwJRepbSo8V00Z4O1ElJxMYd7q5xR5MQkyaATZX5LdhjjwH4TWhCKJAyU8+ny6WWfkm28bjdo8lds1Q8Mk1VZ2L3DFTAqvKm9BKZWu3ao/d09Ge0iXp7KJGJwcFuaFb+EPrBd/mxkmbzJNd9j0XLhK0UUZsNey1CVfHNoWKvevxarXGoDLQITdws79JcAIfcZkHVJ5T47wfme9KtKilpZ6aAbZ1C5tQzbmLf6mvJKAKP7gvDkruybSq+Zd3GKQQYIWqCLXzNIkg2oz3jHlnQXlTw8ifHnVcGYD2h9XrYKjNJZnSR1y62Z8FURWZE881mNk3fPyJepLjBhG/y+dmNSxxS3U2lEO8=
branches:
  only:
  - main