sudo: false
language: ruby
cache:
  directories:
  - "/home/travis/.rvm/"
rvm:
- 2.6.6
install:
- bundle install
before_script:
- git config --global user.email "jnu2345@gmail.com"
- git config --global user.name "wind-flow"
script: bundle exec rake site:deploy --quiet
env:
  global:
  - secure: O+1eAn8imGVeqdoTynOl7uD/WYlXQpd9EgdZ86/kZjr9wvynJvMaJ7aVCUrElA4/HmaZ+TnR8ZyAO062AeNDm4jz290tpByxUSI1ucpTF5dwqG+QEfwKFApl8+wuUQ2BeDBZ5SYjl75OrW57CCQy5qkfYnPiRhhxiJCTHchmi81UW03rtCg0YRA/72TPtoRWBKDk0IOTUw5ZBM0JkvBVb+/K8aUD8WHGvPeBs19WFZmtzlxo/lZpMW0Ww5F7dZ1T295jfIm8pZjVgMQQBxzrL5+K/KfaL/P4DEiqRGU5nJPtIg5cb10uiTUroUURS4+R4CHgJQc7XGI+NZDPpHhXwscUoEj1QqwNZhgijyJKFBgHLi4K6tVaHPa4/DAzjDJRkVvPIrpD4GNU+Q20cU2VnSkV6qUB2w7+NCCbi6nxiDFofYglOuom0w5Mib9nX9BxN+naGlXrEQq/89w0HOaaGic8u9WoOSb76nwSfSWW8DfdQTQmQ/boyvr3oxhWv5juJxPbJuXWQGQbgiDqGHv+RbLPbs/Cz93mhaSjD4Kd+a+S3p94AE2A91RL3O1hrkcV1G3XtqfMPCdgDKosRV8hwgKd2yqzsAXgJgBka42Y1aO6fOS2zrlQvBkwXXFfJ8IvIAc6qw4xdpyK4kIqF0AdEDaweWOgdvdtJxNRmKdIVPY=
  - secure: nBsYeA5xzvDOd8HLKUne/+rllnL3njE1ZGtWTc4kQ16U7EO3LNhT+wS/zNyeOt7Ve7aYqXcThYG/12zBI5DtY7y4srYjt+xYIUH7TqIFFJ5O1weyReDKgvOD7P/qOFactJuCzkPwZN71Dg8/MlekCTdAqSs/pcSyUmNwg0/gyFaUqGXBxNUf3pDpckGHRvLDqJ2CV0M4SZ18r7xaz5Jj3Jc/tIyXklCyOkP+mXykjzwJ7CySF40QHMTVz+ZryEHj1Ul8UmGvwslDYPWsJ0Z7gWsLOmSHmQ/5P5Ag8idJbrVNG1J1jbA9yaZ96Fd4WwyC4h7MSo+z2ekU1OLy3kA26j+NITAVqrakTPREYea3ZkggJI8uc90fIlD/cNKKgM5PyXAS7Q4fHMIJCAscSvhGCwxI1GqK+bg9Y0ERbqM7YWzgLKvFWKrNyQptTeyM4qsdfDx09en4SR0d0EKqhyKK0DVu2OT2LmaL+Ga5/2K4ypMudpKfcHy+KTXiayjPTLDse1Sk+XJo47mWOzqTOL3cluxGId4ZRmhnTgLmdhkd5OfimeNncbyDcMooMt38gLxKDOzCavsb8aaLjqODM3KxGBfz8eahWJGH3CY/VxtuUZQelcmnDnNKu0y9UVfi9ieWISPf1mN7MlbZPyGT3imf98pseSUmQikuZkJVy6GLfAg=
branches:
  only:
  - main
