# Jekyll configuration
markdown: kramdown #rdiscount, redcarpet, kramdown
# kramdown : markdown의 개조판.
# markdown에서 불편한 사항을 개선한 형태.
words_per_minute: 200

# MyData
owner:
  name:           wind-flow
  avatar:         assets/images/profile.png
  bio:            "Security, Analyst, Finance"
  email:          jnu2345@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:
  facebook:
  github: wind-flow
  stackexchange:
  linkedin: in/gunwoo-kim-967265128/
  instagram:
  flickr:
  tumblr:
  # google plus id, include the '+', eg +mmistakes
  google_plus:

highlighter: rouge
# text highlighter로 rouge이용
# 2016.02월 이후로 syntax highlighter는 rouge만 지원.
# Pygments 사용불가.

paginate: 20
# 작성한 모든 post를 하나의 페이지에 열거할 수 없으니
# pagination이 필요하고 몇개의 post를 하나의 page에서
# 보여줄 건지를 설정.

language: 'en-uk'
# 언어 설정

url: https://wind-flow.github.io
# Google Search Console에서 사용하는 sitemap.xml 생성시
# 이 url key값이 존재하지 않으면 sitemap.xml이
# 정상적으로 생성되지 않는다.
# 또한 disqus(댓글시스템)를 이용하기 위해서도 필요.
# 자신의 github page url을 입력
# ( https://your_github_id.github.io 형식 )

baseurl: /

# Website info
title: wind-flow Tech Blog
# 자신의 blog title.

description: wind-flow Tech Blog
# blog home에 표시될 blog에 대한 전반적인 설명.

cover: assets/images/sevenpuzzle.jpg
# blog home에 표시될 blog cover image.

logo:
logo_dark:

favicon: assets/built/images/wind-flow.png
# favicon으로 사용할 image

production_url: https://wind-flow.github.io/
# 최종적으로 blog가 운영될 url

source_url: https://github.com/wind-flow/GithubPageSourceRepo/
# blogmaker(jekyll source folder)에 대한 github repository

# Social info
navigation: True
# Navigation bar link를 보여줄건지 여부

subscribers: True
# subscriber 기능을 사용할건지의 여부
# 저는 약간의 수정을 통해 subscriber 기능대신
# lunr.js를 이용한 검색 기능으로 대체 사용했습니다.
# 검색기능으로 대체하기 위해서
# `_includes/subscribe-form.html` 파일의 수정이 필요합니다.

twitter:
facebook:
# 만약 twitter와 facebook을 이용하면 username을 입력

# Disqus
disqus: True
disqus_shortname: xxxxxxxx
# disqus는 온라인 댓글 시스템. 댓글 기능을 사용하기 위해
# disqus를 이용할 것인지 여부와 만약 사용하면
# disqus shortname을 입력 ( disqus username이 아님 )


# Google Analytics
google_analytics: UA-xxxxxxxx-x # replace with your GA tracking identifier
# Google Analytics을 사용할 경우 GA tracking identifier를 입력

# Permalinks
permalink: /:title
# permalink: /author/:author
# permalink: /tag/:title
# 각각의 post에 고정주소를 어떤 방식으로 할당할 것인지를 결정
# 이 값을 바꾸면 작성한 포스트의 저장위치나 파일이름이 변경된다.

# gems and other configs
plugins: [jekyll-paginate, jekyll-feed, jekyll-gist]
 
feed:
  path: feed.xml

# Travis-CI 설정입니다.
safe: False
lsi: False

username: wind-flow
repo: GithubPageSourceRepo
# username : travis-ci와 연동하는 github의 username
# repo: travis-ci와 연동하는 github의 repository이름
# https://github.com/<username>/<repository>

branch: main
# 사용할 branch명

relative_source:

destination: ./output/
# compile된 결과가 생성되는 폴더
# 이 폴더안의 내용이 우리가 운영하는 블로그 내용이 컴파일되서 들어간다.
# 이 폴더안의 내용을 github repository(https://username.github.io)에 push
# 만약 Travis-CI를 이용할 예정이면 이 부분을 git submodule로
# github repository(https://username.github.io)에 연결해야 한다.

# asciidoc: {}
# asciidoctor:
#   base_dir: :docdir
#   safe: unsafe
#   attributes:
#     - idseparator=_
#     - source-highlighter=coderay
#     - icons=font  

# exclude는 Jekyll컴파일 시 destination에 포함될 필요가
# 없는것들을 명시한다. (node_modules와 필요없는 것들은 제외)
exclude:
  # - README.md
  # - Rakefile
  # - Gemfile
  # - Gemfile.lock
  # - changelog.md
  # - "*.Rmd"
  # - vendor
  # - .travis.yml
  # - node_modules
  # - assets/css
  # - assets/images
#   - _posts/angular
#   - _posts/et-cetera
#   - _posts/python
#   - _posts/typescript
#   - _posts/jekyll
#   - _posts/iot
#   - _posts/r
#   - _posts/economy
theme: jekyll-theme-hacker