name: Jekyll CI

on:
  push:
    branches:
      - main

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      # - name: Create issue using REST API
      #   run: |
      #     curl --request POST \
      #     --url https://api.github.com/repos/${{ github.repository }}/issues \
      #     --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
      #     --header 'content-type: application/json' \
      #     --data '{
      #       "title": "Automated issue for commit: ${{ github.sha }}",
      #       "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
      #       }' \
      #     --fail  
      - uses: actions/checkout@v2
        with:
          # persist-credentials: false
          github_token: ${{ secrets.GITHUB_TOKEN }}  
        # env:
        #   GITHUB_TOKEN: N5yyr1tzyaBp+Yv5RnJFoy1vSZ19HwtlMNfVumUDfnCNY/OrEO64RJgjwCqEx4fZOmBgVdzMAxlIu/huMvEaDQA5Wvb7ll7ZwXeBkTOLWkN/7V9k1QnBeQXLnxHmt47Asek9ueMXpk/U/fr3y3+7Qxow7TLAZFh8mzipKh7G6QK0Oz1sEQ3Rei6weF+rmNMrFuTauZZLNIDxHSiXsAmFctoRicfISGiRZrzVufNdR+srtIQA2Mg8ou+g7QB0942KFFa8uKv9ozCnLtJ81FRft36iJbFMuthuyPwqZSWxF3tTRB1k4ZRtTF+TfLk3kPFJBsolelC2WSaQuP7FfKLzXP66uM+oP18EkfBw+5r6k07fjX8n0lMWfiy4d3LRNCqMcpLI0pi/GatT1bP300RwQVFgwZSQuhDdqJn32MQP833nT3o5po8MNr5fZfV4GdYQgFu9S2LEAMITv2sSZxwRTBPbdDF2sJxra62xbC8SWJTHWdv1em9QxvFW91f9K3rX0wJcRKTPxZ7ziwQ8pvBdDQ5bWie1u2nOcp+JRanIZRUzE0y8WjXpBngH9qIzguNjy4oFeW6n2xFtFmWfBeR8q5RnRt9UJA9x9uwaXo7aWMrsKf8PyWRsH/sKKCvv/lc7iHnJSziBdnLMJW4P1fYMO7mfiQ5bnwE5jVp13s3F2gw=
      # Use GitHub Actions' cache to shorten build times and decrease load on servers
      # - uses: webfactory/ssh-agent@v0.5.4
      #   with:
      #       ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: install deploy keys
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
          run: gem install bundler:2.2.28 | gem update --system
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name : bundle install
        run: bundle install
      - name : bundle update
        run  : bundle update --bundler
      - name : set email
        run  : git config --global user.email "jnu2345@gmail.com"
      - name : set user name
        run  : git config --global user.name "${GITHUB_ACTOR}"
      - name : rake build
        run : git rm --cached . -rf && bundle exec rake site:deploy --quiet
        env:
          github-token: ${{secrets.GITHUB_TOKEN}}